[package]
name = "crab_os"
version = "0.1.0"
authors = ["Toby Hughes <tobywhughes@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.8.0"